export ZSH=/Users/shiddy/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh
export PATH="$PATH:/Users/shiddy/bin"

# If you ever install rbenv you should add these to your PATH
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias vi=vim
alias gs="git status"
alias todo='git status --porcelain | grep -v "^[ |??]" | sed -e "s/[A-Z] *//" | awk "{print $1}" | while read line; do grep -H -e "TODO" -e "XXX" -e "FIXME" -e "NOTE" $line; done'
alias box='boxes -d shell -p a1h2 <<< '
alias sub='git submodule update --recursive --init'
alias tagtime='ctags -R --exclude=.git --languages=python --python-kinds=-i --exclude=node_modules --exclude=test --exclude=venv'
alias mkcdir

mkcdir(){
  mkdir -p -- "$1" && cd -P -- "$1"
}

# Run Tmux on new terminal start
# if command -v tmux>/dev/null; then
#   [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
# fi

if [ -f "$HOME/.zshrc.local" ]; then source "$HOME/.zshrc.local"; fi
