# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=/Users/shiddy/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Sometimes it's a good idea to have local binaries in a local place
export PATH="$PATH:/Users/shiddy/bin"

# If you ever install rbenv you should add these to your PATH
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# I use vi bindings to move around because RMS eats things he picks off the ground with his feet
set -o vi

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias vi=vim
alias gs="git status"
alias javadocs='javadoc -author -version -noqualifier "java.lang" -link "https://docs.oracle.com/javase/8/docs/api/" -d "docs" '
alias junitc='javac -cp .:junit-4.12.jar:hamcrest-core-1.3.jar '
alias junit='java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore '
alias vsc='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'
alias pyl='flake8 --config=~/.config/pycodestyle '
alias oops='echo "$(date)" "$@" >> ~/oops.txt'
alias box='boxes -d shell -p a1h2 <<< '
alias sub='git submodule update --recursive --init'
alias mkcdir

mkcdir(){
  mkdir -p -- "$1" && cd -P -- "$1"
}

# Run Tmux on new terminal start
if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/shiddy/programming/work/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/shiddy/programming/work/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/shiddy/programming/work/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/shiddy/programming/work/google-cloud-sdk/completion.zsh.inc'; fi
