config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
dotfiles:
  f_bash_profile:
    src: .bash_profile
    dst: ~/.bash_profile
    link: link
  f_bash_profile.local:
    src: .bash_profile.local
    dst: ~/.bash_profile.local
    link: link
  f_zshrc:
    src: .zshrc
    dst: ~/.zshrc
  f_zshrc_local:
    src: .zshrc_local
    dst: ~/.zshrc_local
  f_init.vim:
    src: .config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_tmux.conf:
    src: .tmux.conf
    dst: ~/.tmux.conf
profiles:
  zsh-neovim:
    dotfiles:
    - f_zshrc
    - f_zshrc_local
    - f_init.vim
    - f_tmux.conf
