actions:
  pre:
    install-pack: v=v0.2.2 && os=x86_64-apple-darwin && wget https://github.com/maralla/pack/releases/download/$v/pack-$v-$os.tar.gz && tar -xf pack-$v-$os.tar.gz && pack-$v-$os.tar.gz/pack /usr/local/bin/
    install-vim-plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    install-vim-completer: mkdir -p ~/.vim/pack/completor/start && git clone https://github.com/maralla/completor.vim.git ~/.vim/pack/completor/start/completor && pack install maralla/completor.vim
    make-swp: touch ~/.tmux.conf.local && mkdir -p ~/.vim/backup && mdkir -p ~/.colors
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  longkey: false
dotfiles:
  f_battlestation-iterm-profile.json:
    dst: ~/.colors/battlestation-iterm-profile.json
    src: colors/battlestation-iterm-profile.json
  f_gruvbox.itermcolors:
    dst: ~/.colors/gruvbox.itermcolors
    src: colors/gruvbox.itermcolors
  f_oceanicnext.itermcolors:
    dst: ~/.colors/oceanicnext.itermcolors
    src: colors/oceanicnext.itermcolors
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  battlestation:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_tmux.conf
    - f_tellgruv.vim
    - f_gruvbox.itermcolors
    - f_oceanicnext.itermcolors
    - f_battlestation-iterm-profile.json
