config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: true
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    link: link
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    link: link
  f_bash_profile:
    src: .bash_profile
    dst: ~/.bash_profile
    link: link
  f_bash_profile.local:
    src: .bash_profile.local
    dst: ~/.bash_profile.local
    link: link
profiles:
  linux:
    dotfiles:
    - f_vimrc
    - f_tmux.conf
    - f_bash_profile
    - f_bash_profile.local
  macos:
    dotfiles:
    - f_vimrc
    - f_tmux.conf
    - f_bash_profile
    - f_bash_profile.local
