format = """
[](#44386e)\
$os\
$battery\
[](bg:#2D1052 fg:#44386E)\
$directory\
[](fg:#2D1052 bg:#F0E8FF)\
$git_branch\
$git_status\
[](fg:#F0E8FF bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#44386E"
style_root = "bg:#44386E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#44386E"
disabled = true # Disabled by default

[battery]
# style = "bg:#44386E"
# format = '[$user ]($style)'
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰁾'
empty_symbol = '󰂎'
format = '[$symbol]($style)'
disabled = false
# show_always = true

[[battery.display]]
threshold = 10
style = "fg:red bg:#44386E"

[[battery.display]]
threshold = 30
style = "fg:yellow bg:#44386E"

[[battery.display]]
threshold = 50
style = "fg:orange bg:#44386E"

[[battery.display]]
threshold = 100
style = "bg:#44386E"

[directory]
style = "bg:#2D1052"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Programming" = "󱃖 "
"tmp" = " "
"~" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
# style = "fg:#262626 bg:#86BBD8"
# format = '[ $symbol $context ]($style) $path'
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#262626 bg:#F0E8FF"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#262626 bg:#F0E8FF"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#262626 bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ 󱄳 $time ]($style)'
